// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtfbhtflgcqcvrkqpurv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0ZmJodGZsZ2NxY3Zya3FwdXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjA3ODAsImV4cCI6MjA1ODgzNjc4MH0.iYzOQeREWzaZqgUcMD_dYRliM17VpFVwb-IqvYt1Ug8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);